server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: mohammad
    password: passer
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
#spring.jpa.show-sql: true
